#!/usr/bin/env node
// dual-audit:package-file (installed by dual-audit; ownership marker — do not remove)
// profile.js — parse, validate and compile a dual-audit profile.
//
// Two jobs:
//   check    <user.yaml> [base-dir]           validate syntax and schema, report problems
//   compile  <user.yaml> <panel.js> [base-dir] write the generated PROFILE block into the
//                                              installed panel
//   show     <user.yaml> [base-dir]           print the compiled profile as JSON
//
// WHY COMPILE INSTEAD OF READ AT RUN TIME: the panel runs inside a workflow sandbox with no
// filesystem access, so it cannot read a profile itself. The profile is therefore compiled into
// the installed panel between two markers, together with a hash of the source file, and
// `dual-audit doctor` reports when the source has changed since.
//
// The YAML SUBSET is deliberately small and every unsupported construct is a LOUD error rather
// than a quiet misreading. Supported: nested maps by two-space indentation, lists of scalars,
// lists of maps, single-line plain or quoted scalars, `[]` for an empty list, `#` comments.
// Not supported: tabs for indentation, block scalars (| >), anchors and aliases (& *), flow
// maps ({}), multiple documents, multi-line strings.

'use strict'
const fs = require('node:fs')
const path = require('node:path')
const crypto = require('node:crypto')

const MARK_START = '// >>> DUAL-AUDIT PROFILE (generated by `dual-audit profile apply` — do not edit by hand) >>>'
const MARK_END = '// <<< END DUAL-AUDIT PROFILE <<<'

class ProfileError extends Error {}

// ---------------------------------------------------------------------------
// YAML subset parser
// ---------------------------------------------------------------------------

function stripComment(line) {
  // A '#' only starts a comment at the start of the line or after whitespace, and never inside
  // a quoted scalar. Getting this wrong would silently truncate a value containing '#'.
  let quote = null
  for (let i = 0; i < line.length; i++) {
    const c = line[i]
    if (quote) { if (c === quote) quote = null; continue }
    if (c === '"' || c === "'") { quote = c; continue }
    if (c === '#' && (i === 0 || /\s/.test(line[i - 1]))) return line.slice(0, i)
  }
  return line
}

function parseScalar(raw, where) {
  const s = raw.trim()
  if (s === '') return ''
  // Flow sequence: [a, b, "c d"]. Common enough in hand-written YAML that not supporting it
  // would mean silently reading a list as a string, which is exactly the class of quiet
  // misreading this parser exists to avoid.
  if (s[0] === '[') {
    if (s[s.length - 1] !== ']') throw new ProfileError(`${where}: unterminated flow list — keep it on one line`)
    const body = s.slice(1, -1).trim()
    if (body === '') return []
    const items = []
    let cur = '', quote = null
    for (let i = 0; i < body.length; i++) {
      const c = body[i]
      if (quote) { cur += c; if (c === quote) quote = null; continue }
      if (c === '"' || c === "'") { quote = c; cur += c; continue }
      if (c === ',') { items.push(cur); cur = ''; continue }
      if (c === '[' || c === '{') throw new ProfileError(`${where}: nested flow collections are not supported`)
      cur += c
    }
    if (quote) throw new ProfileError(`${where}: unterminated quoted string inside a flow list`)
    items.push(cur)
    // An empty item — `[a, , b]`, or the trailing comma in `[a, b, ]` — used to be dropped silently.
    // Quietly returning a list of a different length than the one written is the exact behaviour this
    // parser exists to avoid, so it is refused instead. Say what to change rather than guessing.
    for (const raw of items) {
      if (raw.trim() === '') throw new ProfileError(`${where}: empty item in a flow list — remove the stray comma rather than leaving a gap`)
    }
    return items.map(x => parseScalar(x, where))
  }
  if (s === 'true') return true
  if (s === 'false') return false
  if (s === 'null' || s === '~') return null
  // A value that OPENS with a quote must CLOSE with the same quote. Falling through to the
  // plain-scalar branch instead would silently turn `docs: "missing the closing quote` into the
  // string `"missing the closing quote` — a value that looks non-empty to every downstream check
  // while pointing at nothing. Downstream that is a real fail-open: a project whose `docs` is
  // non-empty satisfies the high-risk anchor requirement, so an audit could converge while the
  // independent reviewer had nothing readable to read.
  if (s[0] === '"' || s[0] === "'") {
    // The closing quote must be a REAL terminator. `"/some/path\"` ends with a quote character,
    // but that quote is escaped, so the string is still unterminated — accepting it would hand
    // back a truncated path that looks perfectly valid to every downstream check.
    const escaped = (() => {
      let n = 0
      for (let i = s.length - 2; i >= 0 && s[i] === '\\'; i--) n++
      return n % 2 === 1
    })()
    if (s.length < 2 || s[s.length - 1] !== s[0] || escaped) {
      throw new ProfileError(`${where}: unterminated quoted string — a value that opens with ${s[0]} must close with an unescaped ${s[0]}`)
    }
    const body = s.slice(1, -1)
    return s[0] === '"' ? body.replace(/\\n/g, '\n').replace(/\\"/g, '"').replace(/\\\\/g, '\\') : body
  }
  if (/^-?\d+$/.test(s)) return parseInt(s, 10)
  for (const bad of ['|', '>', '&', '*', '{', '`']) {
    if (s[0] === bad) {
      throw new ProfileError(`${where}: unsupported YAML syntax starting with '${bad}'. ` +
        `This parser accepts single-line scalars only — quote the value, or keep it on one line.`)
    }
  }
  return s
}

function parseYamlSubset(text, file) {
  const rawLines = text.split(/\r\n|\n/)
  const lines = []
  let sawDocStart = false
  rawLines.forEach((l, i) => {
    if (/^\t/.test(l) || /^ *\t/.test(l)) {
      throw new ProfileError(`${file}:${i + 1}: tab used for indentation. Use spaces.`)
    }
    const body = stripComment(l)
    if (body.trim() === '') return
    if (/^---\s*$/.test(body)) {
      // One document per file. A second `---` would otherwise merge two documents into one map,
      // so a profile could contain settings that appear to be overridden but are not.
      if (sawDocStart || lines.length) {
        throw new ProfileError(`${file}:${i + 1}: multiple YAML documents are not supported — keep one profile per file`)
      }
      sawDocStart = true
      return
    }
    lines.push({ n: i + 1, indent: body.match(/^ */)[0].length, text: body.trim() })
  })

  let pos = 0
  const peek = () => lines[pos]

  function parseBlock(indent) {
    const first = peek()
    if (!first) return null
    return first.text.startsWith('- ') || first.text === '-' ? parseList(indent) : parseMap(indent)
  }

  function parseMap(indent) {
    // Null prototype, deliberately. On an ordinary object literal, assigning the key `__proto__` sets
    // the prototype instead of creating a property: the line parses, the key vanishes from the result,
    // and no error is raised — a silent drop in a parser whose entire contract is that it never reads
    // one thing as another. With no prototype, `__proto__` is an ordinary key that then fails schema
    // validation out loud.
    const out = Object.create(null)
    while (pos < lines.length) {
      const l = peek()
      if (l.indent < indent) break
      if (l.indent > indent) throw new ProfileError(`${file}:${l.n}: unexpected indentation`)
      if (l.text.startsWith('- ')) break
      const m = /^([A-Za-z_][A-Za-z0-9_-]*)\s*:(.*)$/.exec(l.text)
      if (!m) throw new ProfileError(`${file}:${l.n}: expected "key: value", got ${JSON.stringify(l.text)}`)
      const key = m[1]
      const rest = m[2].trim()
      // The compiled profile is embedded in the panel as a JavaScript object LITERAL, and in a literal
      // `"__proto__":` sets the prototype rather than adding a property. Carrying such a key through
      // would mean the profile the panel ends up with is not the profile that was validated.
      if (key === '__proto__') {
        throw new ProfileError(`${file}:${l.n}: "__proto__" cannot be used as a key — it would change the shape of the compiled profile rather than adding a setting`)
      }
      if (Object.prototype.hasOwnProperty.call(out, key)) {
        throw new ProfileError(`${file}:${l.n}: duplicate key "${key}" — one of the two values would be silently discarded`)
      }
      pos++
      if (rest !== '') {
        out[key] = parseScalar(rest, `${file}:${l.n}`)
      } else {
        const next = peek()
        out[key] = (next && next.indent > indent) ? parseBlock(next.indent) : null
      }
    }
    return out
  }

  function parseList(indent) {
    const out = []
    while (pos < lines.length) {
      const l = peek()
      if (l.indent < indent) break
      if (l.indent > indent) throw new ProfileError(`${file}:${l.n}: unexpected indentation inside a list`)
      if (!l.text.startsWith('- ') && l.text !== '-') break
      const rest = l.text === '-' ? '' : l.text.slice(2).trim()
      if (/^([A-Za-z_][A-Za-z0-9_-]*)\s*:/.test(rest)) {
        // A list item that is a map: re-indent the inline part and keep reading siblings.
        const itemIndent = l.indent + 2
        lines[pos] = { n: l.n, indent: itemIndent, text: rest }
        out.push(parseMap(itemIndent))
      } else if (rest === '') {
        pos++
        const next = peek()
        out.push(next && next.indent > indent ? parseBlock(next.indent) : null)
      } else {
        pos++
        out.push(parseScalar(rest, `${file}:${l.n}`))
      }
    }
    return out
  }

  const doc = parseBlock(0)
  if (pos < lines.length) throw new ProfileError(`${file}:${lines[pos].n}: could not parse this line`)
  return doc === null ? {} : doc
}

// ---------------------------------------------------------------------------
// Schema validation
// ---------------------------------------------------------------------------

const ROUTE_VALUES = ['full', 'light']

// ---------------------------------------------------------------------------
// What this package may ever install
// ---------------------------------------------------------------------------

// The complete, fixed set of destinations. ONE source of truth: the installer builds its plan from
// it, and uninstall and doctor refuse to act on any manifest entry that is not in it.
//
// Without that refusal the manifest was self-certifying — anything shaped like `{version, files}`
// was accepted as this package's ownership record, and the paths inside it were then trusted. A
// stale manifest from another installation, or a hand-written one, could name any file on the
// machine and have it treated as ours to overwrite or delete. The set below cannot be widened by
// editing a manifest, because it is not read from one.
function installTargets(dirs) {
  const claude = String(dirs.claudeDir).replace(/\/+$/, '')
  const bin = String(dirs.binDir).replace(/\/+$/, '')
  const share = String(dirs.shareDir).replace(/\/+$/, '')
  return [
    { rel: 'runtime/core/dual-audit-panel.js', dst: `${claude}/workflows/dual-audit-panel.js`, mode: '644' },
    { rel: 'runtime/claude-controller/dual-audit-run.js', dst: `${claude}/workflows/dual-audit-run.js`, mode: '644' },
    { rel: 'runtime/codex-auditor/dual-audit-codex-readonly.md', dst: `${claude}/agents/dual-audit-codex-readonly.md`, mode: '644' },
    { rel: 'skills/dual-audit/SKILL.md', dst: `${claude}/skills/dual-audit/SKILL.md`, mode: '644' },
    { rel: 'skills/light-audit/SKILL.md', dst: `${claude}/skills/light-audit/SKILL.md`, mode: '644' },
    { rel: 'runtime/core/dual-audit', dst: `${bin}/dual-audit`, mode: '755' },
    { rel: 'runtime/codex-auditor/dual-audit-codex', dst: `${bin}/dual-audit-codex`, mode: '755' },
    { rel: 'runtime/codex-auditor/dual-audit-lint', dst: `${bin}/dual-audit-lint`, mode: '755' },
    { rel: 'runtime/core/profile.js', dst: `${share}/lib/profile.js`, mode: '644' },
    { rel: 'profiles/default.yaml', dst: `${share}/profiles/default.yaml`, mode: '644' },
    { rel: 'profiles/research.yaml', dst: `${share}/profiles/research.yaml`, mode: '644' },
    { rel: 'profiles/user.example.yaml', dst: `${share}/profiles/user.example.yaml`, mode: '644' },
  ]
}

// The absolute paths named inside a free-text `docs` value. One reader, so the lexical check, the
// on-disk check and the compile-time refusal cannot disagree about which paths a profile claims.
function docsPaths(value) {
  return (String(value == null ? '' : value).match(/(^|\s)(\/[^\s,;]+)/g) || [])
    .map(m => {
      let v = m.trim().replace(/[,;]+$/, '')
      // A trailing '.' is usually sentence punctuation ("see /a/b.md.") and is stripped — but NOT
      // when the final segment IS '.' or '..'. Stripping it there rewrote the user's path into a
      // different directory behind their back, and turned `/tmp/..` (which resolves to `/`) into
      // `/tmp`, hiding a degenerate anchor by silently making it a real one.
      const last = v.split('/').pop()
      if (last !== '.' && last !== '..') v = v.replace(/\.+$/, '')
      return v
    })
    .filter(Boolean)
}

// Whether an absolute path names anything at all. `/`, `//`, `/.`, `/..`, `/../..` do not: every
// segment is empty, "." or "..", so the path resolves to a directory containing no evidence.
function namesSomething(p) {
  // Lexically normalised FIRST: `/tmp/..` has a real-looking segment but resolves to `/`, so a
  // segment-only test called it a valid anchor. What matters is where the path lands, not how it
  // is spelled.
  const norm = require('path').posix.normalize(String(p))
  return norm !== '/' && norm.split('/').some(seg => seg !== '' && seg !== '.' && seg !== '..')
}

// On-disk problems with a profile's anchors. Lexical validation cannot see these, and the panel
// has no filesystem access, so this is the only layer that can. `check` reports them; `compile`
// refuses on them — an anchor that reads nothing is worse than no anchor, because the anchor gate
// counts it as satisfied.
function docsFsIssues(data) {
  const fs = require('fs')
  const out = []
  for (const pr of (Array.isArray(data && data.projects) ? data.projects : [])) {
    for (const abs of docsPaths(pr && pr.docs)) {
      let st = null
      try { st = fs.statSync(abs) } catch (e) { st = null }
      if (!st) {
        out.push(`projects[${pr.id}]: docs path ${abs} does not exist on this machine — the independent reviewer would read nothing from it`)
        continue
      }
      if (!st.isFile() && !st.isDirectory()) {
        // /dev/null is the clean example: it exists, it is readable, and it yields nothing.
        out.push(`projects[${pr.id}]: docs path ${abs} is not a regular file or directory — the independent reviewer would read nothing from it`)
        continue
      }
      // stat() answers "is there something here", not "can the reviewer read it". It succeeds on a
      // mode-000 file, because it needs search permission on the parent directory and nothing on the
      // file itself. Checking only the type therefore admitted exactly the anchors this function's
      // own contract rejects: present, unreadable, and counted as satisfying the high-risk anchor gate.
      try { fs.accessSync(abs, fs.constants.R_OK) }
      catch (e) {
        out.push(`projects[${pr.id}]: docs path ${abs} exists but is not readable by you — the independent reviewer would read nothing from it`)
        continue
      }
      // Readable but empty is the same failure wearing a different hat. An anchor that yields no bytes
      // satisfies the gate while providing nothing to anchor to, which is worse than declaring no anchor
      // at all: the gate reports that the claim was grounded.
      if (st.isFile() && st.size === 0) {
        out.push(`projects[${pr.id}]: docs path ${abs} is an empty file — the independent reviewer would read nothing from it`)
        continue
      }
      if (st.isDirectory()) {
        let entries = null
        try { entries = fs.readdirSync(abs) } catch (e) { entries = null }
        if (entries === null) {
          out.push(`projects[${pr.id}]: docs path ${abs} is a directory that cannot be listed — the independent reviewer would read nothing from it`)
        } else if (entries.length === 0) {
          out.push(`projects[${pr.id}]: docs path ${abs} is an empty directory — the independent reviewer would read nothing from it`)
        }
      }
    }
  }
  return out
}

function validate(profile, file) {
  const errors = []
  const warnings = []
  const isObj = (v) => v && typeof v === 'object' && !Array.isArray(v)

  if (!isObj(profile)) { errors.push(`${file}: the profile must be a map`); return { errors, warnings } }
  if (profile.version !== 1) errors.push(`${file}: "version" must be 1 (got ${JSON.stringify(profile.version)})`)
  if (profile.customized !== undefined && typeof profile.customized !== 'boolean') {
    errors.push(`${file}: "customized" must be true or false (got ${JSON.stringify(profile.customized)})`)
  }
  if (profile.base !== undefined && !['default', 'research'].includes(profile.base)) {
    errors.push(`${file}: "base" must be default or research (got ${JSON.stringify(profile.base)})`)
  }

  const areas = profile.critical_areas
  if (areas !== undefined && areas !== null && !Array.isArray(areas)) {
    errors.push(`${file}: "critical_areas" must be a list`)
  } else if (Array.isArray(areas)) {
    areas.forEach((a, i) => {
      const at = `${file}: critical_areas[${i}]`
      if (!isObj(a)) { errors.push(`${at}: each entry must be a map with name/keywords/route`); return }
      if (!a.name || typeof a.name !== 'string') errors.push(`${at}: "name" is required`)
      if (!Array.isArray(a.keywords) || a.keywords.length === 0) {
        errors.push(`${at}: "keywords" must be a non-empty list — an area with no keywords can never match`)
      } else {
        a.keywords.forEach((k) => {
          if (typeof k !== 'string' || k.trim() === '') { errors.push(`${at}: empty keyword`); return }
          if (k.trim() === '*') errors.push(`${at}: keyword "*" matches everything, so every request would become a full audit`)
          else if (k.trim().length < 3) warnings.push(`${at}: keyword ${JSON.stringify(k)} is very short and will match far more than intended`)
        })
      }
      if (a.route !== undefined && !ROUTE_VALUES.includes(a.route)) {
        errors.push(`${at}: "route" must be one of ${ROUTE_VALUES.join(', ')}`)
      }
    })
  }

  const projects = profile.projects
  if (projects !== undefined && projects !== null && !Array.isArray(projects)) {
    errors.push(`${file}: "projects" must be a list`)
  } else if (Array.isArray(projects)) {
    const seen = new Set()
    projects.forEach((p, i) => {
      const at = `${file}: projects[${i}]`
      if (!isObj(p)) { errors.push(`${at}: each entry must be a map with id/rules/docs`); return }
      if (!p.id || typeof p.id !== 'string') { errors.push(`${at}: "id" is required`); return }
      const key = p.id.trim().toLowerCase()
      if (seen.has(key)) errors.push(`${at}: duplicate project id ${JSON.stringify(p.id)} (matching is case-insensitive)`)
      seen.add(key)
      for (const k of ['rules', 'docs']) {
        if (p[k] !== undefined && p[k] !== null && typeof p[k] !== 'string') errors.push(`${at}: "${k}" must be a string`)
      }
      if (!p.docs || !String(p.docs).trim()) {
        warnings.push(`${at}: no "docs" pointer. A high-risk audit naming this project will still require contextPack.canonical_docs, because the independent reviewer needs something it can read for itself.`)
      } else {
        // `docs` is what SATISFIES the high-risk anchor requirement, so it must actually point at
        // something the reviewer can open. The reviewer runs from a neutral working directory under
        // a restricted HOME, where a relative path or a prose description resolves to nothing — and
        // a reviewer that silently read nothing still returns a confident verdict.
        const found = docsPaths(p.docs)
        if (!found.length) {
          errors.push(`${at}: "docs" contains no absolute path. It is the anchor a high-risk audit relies on, so it must name at least one path beginning with "/".`)
        } else if (!found.some(namesSomething)) {
          // "Starts with a slash" is not the same as "names something". `/`, `//`, `/.`, `/..` and
          // `/../..` all pass a leading-slash test and all resolve to a directory that holds no
          // evidence. Accepting one satisfied the anchor gate with nothing behind it, which is the
          // same fail-open as an unreadable path — just spelled differently.
          errors.push(`${at}: "docs" names only degenerate paths (${found.join(', ')}). A path built entirely from "/", "." and ".." anchors nothing, so a high-risk audit would clear its anchor requirement with no evidence behind it.`)
        }
      }
    })
  }

  if (profile.evidence !== undefined && profile.evidence !== null) {
    if (!isObj(profile.evidence)) errors.push(`${file}: "evidence" must be a map`)
    else if (profile.evidence.brief_note !== undefined && profile.evidence.brief_note !== null &&
             typeof profile.evidence.brief_note !== 'string') {
      errors.push(`${file}: "evidence.brief_note" must be a string`)
    }
  }

  if (profile.routing !== undefined && profile.routing !== null) {
    if (!isObj(profile.routing)) errors.push(`${file}: "routing" must be a map`)
    else {
      for (const k of ['full_audit_triggers', 'light_audit_triggers', 'direct_triggers']) {
        const v = profile.routing[k]
        if (v === undefined || v === null) continue
        if (!Array.isArray(v)) { errors.push(`${file}: "routing.${k}" must be a list`); continue }
        v.forEach((e, i) => {
          if (!isObj(e) || !e.id) errors.push(`${file}: routing.${k}[${i}] must be a map with an "id"`)
        })
      }
    }
  }

  return { errors, warnings }
}

// ---------------------------------------------------------------------------
// Compilation
// ---------------------------------------------------------------------------

function readProfile(file) {
  let text
  try { text = fs.readFileSync(file, 'utf8') }
  catch (e) { throw new ProfileError(`cannot read profile ${file}: ${e.message}`) }
  return { text, data: parseYamlSubset(text, path.basename(file)) }
}

function compile(userFile, baseDir) {
  const { text, data } = readProfile(userFile)
  const baseName = data.base === 'research' ? 'research' : 'default'
  let base = { evidence: { brief_note: '' } }
  if (baseDir) {
    const baseFile = path.join(baseDir, baseName + '.yaml')
    if (fs.existsSync(baseFile)) base = readProfile(baseFile).data
  }
  const noteOf = (d) => (d && d.evidence && typeof d.evidence.brief_note === 'string') ? d.evidence.brief_note.trim() : ''
  // The user's own note wins; otherwise the chosen base contributes its note.
  const brief_note = noteOf(data) || noteOf(base)
  return {
    profile: {
      version: 1,
      name: baseName,
      customized: data.customized === true,
      projects: (Array.isArray(data.projects) ? data.projects : []).map(p => ({
        id: String(p.id).trim(),
        rules: p.rules ? String(p.rules) : '',
        docs: p.docs ? String(p.docs) : '',
      })),
      evidence: { brief_note },
      profile_sha256: crypto.createHash('sha256').update(text).digest('hex'),
    },
    data,
    // The MERGED routing table: the user's own if they wrote one, otherwise the base profile's.
    // It is deliberately absent from `profile` above — the panel reviews, the controller routes —
    // but the controller still has to be able to READ it, and a user profile normally inherits it.
    routing: (data && data.routing) ? data.routing : ((base && base.routing) ? base.routing : {}),
    sha: crypto.createHash('sha256').update(text).digest('hex'),
  }
}

// Where the generated block starts and ends — but ONLY when that is unambiguous.
//
// Both markers must occur EXACTLY ONCE, in order. Locating them with indexOf alone takes the FIRST
// of each, so a file carrying a SECOND, earlier MARK_START widens the span to cover everything from
// that decoy down to the real MARK_END. Every byte before the decoy is untouched, so the base hash
// is unchanged and doctor reports the panel unmodified — while whatever sits inside the widened span
// runs as part of the panel. Reproduced against a real installation: 156 bytes of injected code,
// byte-identical base hash, `dual-audit doctor` exit 0 and "every byte outside the generated profile
// block still matches the manifest".
//
// Returns null when the answer is not unique. Callers must treat null as "no exemption" (hash the
// whole file) or as a refusal — never as "use the first pair and hope".
function markerSpan(src) {
  const count = (needle) => {
    let n = 0
    for (let at = src.indexOf(needle); at !== -1; at = src.indexOf(needle, at + needle.length)) n++
    return n
  }
  if (count(MARK_START) !== 1 || count(MARK_END) !== 1) return null
  const i = src.indexOf(MARK_START)
  const j = src.indexOf(MARK_END)
  if (i < 0 || j < i) return null
  return { i, j }
}

function writeIntoPanel(panelFile, profileObj) {
  let src
  try { src = fs.readFileSync(panelFile, 'utf8') }
  catch (e) { throw new ProfileError(`cannot read the installed panel ${panelFile}: ${e.message}`) }
  const span = markerSpan(src)
  if (!span) {
    throw new ProfileError(`${panelFile}: the generated profile block is missing, damaged, or appears ` +
      `more than once. Splicing on a guessed pair of markers would overwrite the wrong region of the ` +
      `panel. Reinstall rather than editing the panel by hand.`)
  }
  const { i, j } = span
  const head = src.slice(0, i)
  const tail = src.slice(j)
  const block = MARK_START + '\n' +
    '// Compiled from the user profile. The workflow sandbox has no filesystem access, so the\n' +
    '// profile is compiled INTO this file rather than read at run time. `dual-audit doctor`\n' +
    '// reports PROFILE_STALE when the profile file has changed since this block was generated.\n' +
    'const PROFILE = ' + JSON.stringify(profileObj) + '\n'
  fs.writeFileSync(panelFile, head + block + tail)
}

// The hash of everything OUTSIDE the generated profile block. `profile apply` rewrites that block,
// so the panel's whole-file hash legitimately changes — but nothing else in it may. Recording this
// lets uninstall and doctor VERIFY a "mutable" file instead of exempting it from verification,
// which is what turned "removes only what still matches" into "removes the panel unconditionally".
function baseSha(panelFile) {
  const crypto = require('crypto')
  const src = fs.readFileSync(panelFile, 'utf8')
  // No markers, or an ambiguous pair: nothing is exempt, so the base IS the whole file. A panel whose
  // block was deleted — or one carrying a decoy marker that would widen the exempt span — therefore
  // fails the comparison rather than silently getting a free pass.
  const span = markerSpan(src)
  const stripped = span ? src.slice(0, span.i) + src.slice(span.j) : src
  return crypto.createHash('sha256').update(stripped, 'utf8').digest('hex')
}

function installedSha(panelFile) {
  const src = fs.readFileSync(panelFile, 'utf8')
  const m = /"profile_sha256"\s*:\s*(?:"([0-9a-f]{64})"|null)/.exec(src)
  return m ? (m[1] || null) : undefined
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function main(argv) {
  const cmd = argv[0]
  try {
    if (cmd === 'check') {
      const file = argv[1]
      const baseDir = argv[2] || null
      const { data } = readProfile(file)
      const { errors, warnings } = validate(data, path.basename(file))
      warnings.forEach(w => console.log('WARN  ' + w))
      errors.forEach(e => console.log('ERROR ' + e))
      if (errors.length) return 1
      if (data.customized !== true) {
        console.log('NOTE  customized: false — automatic routing stays OFF until you fill in ' +
                    'critical_areas and set customized: true. Explicit review requests still work.')
      }
      if (!Array.isArray(data.critical_areas) || data.critical_areas.length === 0) {
        console.log('NOTE  critical_areas is empty — nothing will route automatically to a full audit.')
      }
      // Lexical validation cannot tell whether a path EXISTS or what it is — the panel has no
      // filesystem access, which is exactly why this check runs here, in the CLI, where it does.
      //
      // ERROR, not WARN. `compile` already refuses these, so a warning here described a profile that
      // could never be applied — and doctor, which renders WARN as an advisory note, stayed green and
      // exited 0 for an installation whose anchors had since been deleted or made unreadable.
      const fsIssues = docsFsIssues(data)
      if (fsIssues.length) {
        fsIssues.forEach(e => console.log('ERROR ' + e))
        console.log('ERROR a docs anchor that reads nothing still satisfies the high-risk anchor gate — fix the paths above.')
        return 1
      }
      // `compile` is exercised here too, so a profile that parses but cannot be compiled is
      // reported by `check` rather than surfacing later during an apply.
      compile(file, baseDir)
      console.log('OK    profile syntax and schema are valid')
      return 0
    }

    if (cmd === 'compile') {
      const file = argv[1], panel = argv[2], baseDir = argv[3] || null
      const { data } = readProfile(file)
      const { errors } = validate(data, path.basename(file))
      if (errors.length) { errors.forEach(e => console.log('ERROR ' + e)); return 1 }
      // Compiling is what puts these anchors INTO the panel, where nothing can check them again —
      // the sandbox has no filesystem. So an unreadable anchor is refused here, not warned about.
      // `check` still reports the same issues as warnings, for a profile you are still editing.
      const fsIssues = docsFsIssues(data)
      if (fsIssues.length) {
        fsIssues.forEach(e => console.log('ERROR ' + e))
        console.log('ERROR refusing to compile: a docs anchor that reads nothing still satisfies the high-risk anchor gate.')
        return 1
      }
      const { profile } = compile(file, baseDir)
      writeIntoPanel(panel, profile)
      console.log(`OK    profile compiled into ${panel} (base: ${profile.name}, ` +
                  `${profile.projects.length} project(s), customized: ${profile.customized})`)
      return 0
    }

    if (cmd === 'targets') {
      // Three NUL-terminated fields per entry, not one '|'-joined line. `rel` and `mode` are ours,
      // but `dst` is built from directories the caller names in the environment, and a path may
      // contain any byte but NUL and '/'. A '|' or a newline in one of those directories split a
      // record into pieces on the reading side. NUL is the one byte that cannot appear, so the
      // framing cannot be broken by the data it carries.
      for (const t of installTargets({ claudeDir: argv[1], binDir: argv[2], shareDir: argv[3] })) {
        process.stdout.write(t.rel + '\0' + t.dst + '\0' + t.mode + '\0')
      }
      return 0
    }

    if (cmd === 'routing') {
      // The MERGED routing table, which is what the controller actually routes on. It is
      // deliberately NOT part of the compiled panel block (the panel reviews; the controller
      // routes), and a user profile normally inherits it from its base — so reading the user's
      // own file would show nothing and the documented routing keys would appear to be missing.
      const { routing } = compile(argv[1], argv[2] || null)
      console.log(JSON.stringify(routing || {}, null, 2))
      return 0
    }

    if (cmd === 'base-sha') {
      console.log(baseSha(argv[1]))
      return 0
    }

    if (cmd === 'show') {
      const { profile } = compile(argv[1], argv[2] || null)
      console.log(JSON.stringify(profile, null, 2))
      return 0
    }

    if (cmd === 'installed-sha') {
      const sha = installedSha(argv[1])
      console.log(sha === undefined ? 'MISSING' : (sha === null ? 'NONE' : sha))
      return 0
    }

    console.error('usage: profile.js check|compile|show|installed-sha ...')
    return 2
  } catch (e) {
    if (e instanceof ProfileError) { console.log('ERROR ' + e.message); return 1 }
    throw e
  }
}

if (require.main === module) process.exit(main(process.argv.slice(2)))

module.exports = { parseYamlSubset, validate, compile, writeIntoPanel, installedSha, ProfileError, MARK_START, MARK_END, docsPaths, namesSomething, docsFsIssues, baseSha, installTargets }
